version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start
    ports:
      - "3000:3000"
    volumes:
      - .:/mamutebar
      - gems:/gems


volumes:
  postgres:
  gems:
